import { Network, Shield, Target, Terminal } from "lucide-react";
import { Course } from "./types";

export const coursesData: { [key: string]: Course } = {
  foundations: {
    id: "foundations",
    title: "Cybersecurity Fundamentals",
    description:
      "Essential concepts, terminology, and security principles that form the backbone of cybersecurity knowledge.",
    category: "Fundamentals",
    difficulty: "Beginner",
    duration: "2-3 weeks",
    icon: Shield,
    color: "text-blue-400",
    bgColor: "bg-blue-400/10",
    borderColor: "border-blue-400/30",
    enrolled: true,
    progress: 85,
    lessons: 17,
    labs: 8,
    games: 6,
    assets: 12,
    rating: 4.9,
    students: 8420,
    price: "Free",
    skills: [
      "CIA Triad",
      "Risk Assessment",
      "Compliance",
      "Security Frameworks",
    ],
    prerequisites: "None - Perfect for beginners",
    certification: true,
    instructor: {
      name: "Dr. Sarah Chen",
      title: "Chief Security Officer",
      avatar:
        "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150",
      experience: "15+ years in cybersecurity",
    },
    curriculum: [
      {
        title: "Introduction to Cybersecurity",
        lessons: 6,
        duration: "2h 15min",
        topics: [
          "What is Cybersecurity",
          "Threat Landscape",
          "Security Policy Builder Game",
          "Security Principles",
          "CIA Triad",
          "CIA Triad Implementation Lab",
        ],
        completed: true,
      },
      {
        title: "Risk Management",
        lessons: 5,
        duration: "2h",
        topics: [
          "Risk Assessment",
          "Risk Assessment Simulation Lab",
          "Risk Analysis",
          "Risk Matrix Challenge Game",
          "Risk Mitigation",
        ],
        completed: true,
      },
      {
        title: "Security Frameworks",
        lessons: 6,
        duration: "3h",
        topics: [
          "NIST Framework",
          "Framework Matcher Game",
          "ISO 27001",
          "Policy Development Workshop Lab",
          "COBIT",
          "SOX Compliance",
        ],
        completed: false,
      },
    ],
    learningOutcomes: [
      {
        title: "Understand core cybersecurity principles",
        description:
          "Master the fundamental concepts of information security including the CIA triad, defense in depth strategies, and basic security principles.",
        skills: ["CIA Triad", "Security Principles", "Defense in Depth"],
      },
      {
        title: "Implement risk assessment methodologies",
        description:
          "Learn to identify, analyze, and evaluate security risks using industry-standard frameworks and methodologies.",
        skills: ["Risk Assessment", "Risk Analysis", "Risk Mitigation"],
      },
      {
        title: "Apply security frameworks effectively",
        description:
          "Gain practical experience with major security frameworks including NIST, ISO 27001, and COBIT.",
        skills: ["NIST Framework", "ISO 27001", "COBIT"],
      },
    ],
    labsData: [
      {
        name: "Risk Assessment Simulation",
        description: "Hands-on risk assessment of a fictional company",
        difficulty: "Beginner",
        duration: "45 min",
        skills: ["Risk Analysis", "Documentation"],
      },
      {
        name: "Policy Development Workshop",
        description: "Create security policies for different scenarios",
        difficulty: "Beginner",
        duration: "60 min",
        skills: ["Policy Writing", "Compliance"],
      },
      {
        name: "CIA Triad Implementation",
        description:
          "Practical implementation of confidentiality, integrity, and availability",
        difficulty: "Beginner",
        duration: "30 min",
        skills: ["CIA Triad", "Security Controls"],
      },
      {
        name: "Security Framework Mapping",
        description: "Map security controls to different compliance frameworks",
        difficulty: "Intermediate",
        duration: "75 min",
        skills: ["Framework Analysis", "Control Mapping"],
      },
      {
        name: "Incident Response Planning",
        description:
          "Develop an incident response plan for a simulated organization",
        difficulty: "Intermediate",
        duration: "90 min",
        skills: ["Incident Response", "Planning", "Documentation"],
      },
      {
        name: "Security Awareness Training Design",
        description:
          "Create security awareness training materials for employees",
        difficulty: "Beginner",
        duration: "50 min",
        skills: ["Training Design", "Security Awareness"],
      },
      {
        name: "Threat Modeling Exercise",
        description: "Perform threat modeling on a sample application",
        difficulty: "Intermediate",
        duration: "80 min",
        skills: ["Threat Modeling", "Risk Assessment"],
      },
      {
        name: "Compliance Audit Simulation",
        description: "Conduct a mock compliance audit using industry standards",
        difficulty: "Advanced",
        duration: "120 min",
        skills: ["Auditing", "Compliance", "Documentation"],
      },
    ],
    gamesData: [
      {
        name: "Security Policy Builder",
        description: "Interactive game to build security policies",
        points: 100,
        type: "Strategy",
      },
      {
        name: "Risk Matrix Challenge",
        description: "Calculate and prioritize security risks",
        points: 150,
        type: "Puzzle",
      },
      {
        name: "Framework Matcher",
        description: "Match security controls to appropriate frameworks",
        points: 120,
        type: "Educational",
      },
      {
        name: "CIA Triad Simulator",
        description:
          "Practice implementing confidentiality, integrity, and availability",
        points: 130,
        type: "Simulation",
      },
      {
        name: "Threat Landscape Explorer",
        description: "Navigate through different cybersecurity threats",
        points: 110,
        type: "Adventure",
      },
      {
        name: "Compliance Checker",
        description: "Test your knowledge of security compliance requirements",
        points: 90,
        type: "Quiz",
      },
    ],
    assetsData: [
      { name: "CIA Triad Reference Guide", type: "PDF", size: "2.1 MB" },
      { name: "Risk Assessment Template", type: "Excel", size: "1.5 MB" },
      { name: "NIST Framework Checklist", type: "PDF", size: "850 KB" },
    ],
    enrollPath: "/learn/foundations",
  },
  "linux-basics": {
    id: "linux-basics",
    title: "Linux Command Line Basics",
    description:
      "Master the terminal and basic command-line operations essential for cybersecurity professionals.",
    category: "Fundamentals",
    difficulty: "Beginner",
    duration: "2-3 weeks",
    icon: Terminal,
    color: "text-green-400",
    bgColor: "bg-green-400/10",
    borderColor: "border-green-400/30",
    enrolled: true,
    progress: 70,
    lessons: 24,
    labs: 12,
    games: 8,
    assets: 18,
    rating: 4.8,
    students: 7250,
    price: "Free",
    skills: [
      "Basic Commands",
      "File Navigation",
      "Text Processing",
      "Permissions",
    ],
    prerequisites: "None - Perfect for beginners",
    certification: true,
    instructor: {
      name: "Alex Rodriguez",
      title: "Senior Systems Administrator",
      avatar:
        "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150",
      experience: "12+ years in Linux administration",
    },
    curriculum: [
      {
        title: "Getting Started with Linux",
        lessons: 7,
        duration: "2h 45min",
        topics: [
          "Linux History",
          "Distributions",
          "Terminal Basics",
          "Terminal Speed Challenge Game",
          "Command Structure",
          "Command Line Navigation Challenge Lab",
        ],
        completed: true,
      },
      {
        title: "File System Navigation",
        lessons: 8,
        duration: "3h 15min",
        topics: [
          "Directory Structure",
          "Navigation Commands",
          "File Operations",
          "File System Explorer Game",
          "Wildcards",
          "Advanced Navigation Lab",
        ],
        completed: true,
      },
      {
        title: "Text Processing & Permissions",
        lessons: 9,
        duration: "4h",
        topics: [
          "Text Editors",
          "File Permissions",
          "File Permissions Workshop Lab",
          "Permission Puzzle Game",
          "User Management",
          "Log Analysis with Command Line Lab",
          "Process Control",
        ],
        completed: false,
      },
    ],
    learningOutcomes: [
      {
        title: "Master essential Linux commands",
        description:
          "Learn fundamental commands for file manipulation, navigation, and system administration.",
        skills: ["Command Line", "File Operations", "System Navigation"],
      },
      {
        title: "Understand Linux file system",
        description:
          "Navigate the Linux directory structure and understand file permissions and ownership.",
        skills: ["File System", "Permissions", "Directory Structure"],
      },
      {
        title: "Perform basic system administration",
        description:
          "Manage users, processes, and system resources using command-line tools.",
        skills: ["User Management", "Process Control", "System Administration"],
      },
    ],
    labsData: [
      {
        name: "Command Line Navigation Challenge",
        description:
          "Navigate through complex directory structures using only terminal commands",
        difficulty: "Beginner",
        duration: "30 min",
        skills: ["Navigation", "File Operations"],
      },
      {
        name: "File Permissions Workshop",
        description:
          "Practice setting and modifying file permissions for security",
        difficulty: "Beginner",
        duration: "45 min",
        skills: ["Permissions", "Security"],
      },
      {
        name: "Log Analysis with Command Line",
        description:
          "Analyze system logs using grep, awk, and other text processing tools",
        difficulty: "Intermediate",
        duration: "60 min",
        skills: ["Text Processing", "Log Analysis"],
      },
      {
        name: "Advanced Navigation Lab",
        description: "Master advanced navigation techniques and shortcuts",
        difficulty: "Intermediate",
        duration: "40 min",
        skills: ["Advanced Navigation", "Efficiency"],
      },
      {
        name: "Shell Scripting Basics",
        description: "Create your first shell scripts for automation",
        difficulty: "Intermediate",
        duration: "75 min",
        skills: ["Shell Scripting", "Automation"],
      },
      {
        name: "Process Management Lab",
        description: "Learn to manage and monitor system processes effectively",
        difficulty: "Intermediate",
        duration: "55 min",
        skills: ["Process Management", "System Administration"],
      },
      {
        name: "Network Commands Workshop",
        description: "Use Linux networking commands for troubleshooting",
        difficulty: "Intermediate",
        duration: "65 min",
        skills: ["Networking", "Troubleshooting"],
      },
      {
        name: "System Security Hardening",
        description: "Harden a Linux system against common security threats",
        difficulty: "Advanced",
        duration: "90 min",
        skills: ["System Hardening", "Security"],
      },
      {
        name: "Backup and Recovery Lab",
        description:
          "Implement backup strategies and practice recovery procedures",
        difficulty: "Intermediate",
        duration: "70 min",
        skills: ["Backup", "Recovery", "Data Protection"],
      },
      {
        name: "Performance Monitoring Workshop",
        description: "Monitor system performance and identify bottlenecks",
        difficulty: "Advanced",
        duration: "85 min",
        skills: ["Performance Monitoring", "System Analysis"],
      },
      {
        name: "Container Security Lab",
        description: "Secure Docker containers and implement best practices",
        difficulty: "Advanced",
        duration: "100 min",
        skills: ["Container Security", "Docker"],
      },
      {
        name: "Incident Response with Linux",
        description:
          "Use Linux tools for digital forensics and incident response",
        difficulty: "Advanced",
        duration: "110 min",
        skills: ["Incident Response", "Digital Forensics"],
      },
    ],
    gamesData: [
      {
        name: "Terminal Speed Challenge",
        description: "Complete tasks as quickly as possible using command line",
        points: 80,
        type: "Speed",
      },
      {
        name: "Permission Puzzle",
        description: "Solve file permission challenges step by step",
        points: 120,
        type: "Puzzle",
      },
      {
        name: "File System Explorer",
        description:
          "Navigate complex directory structures in a game environment",
        points: 100,
        type: "Adventure",
      },
      {
        name: "Command Master",
        description: "Master Linux commands through interactive challenges",
        points: 140,
        type: "Educational",
      },
      {
        name: "Process Hunter",
        description: "Find and manage system processes in real-time scenarios",
        points: 160,
        type: "Simulation",
      },
      {
        name: "Log Detective",
        description: "Analyze system logs to solve security incidents",
        points: 180,
        type: "Investigation",
      },
      {
        name: "Shell Scripting Challenge",
        description: "Create powerful shell scripts to automate tasks",
        points: 200,
        type: "Programming",
      },
      {
        name: "Linux Security Fortress",
        description: "Secure a Linux system against various attack scenarios",
        points: 220,
        type: "Defense",
      },
    ],
    assetsData: [
      { name: "Linux Command Cheat Sheet", type: "PDF", size: "1.2 MB" },
      { name: "File Permission Calculator", type: "Tool", size: "500 KB" },
    ],
    enrollPath: "/learn/linux-basics",
  },
  "networking-basics": {
    id: "networking-basics",
    title: "Networking Fundamentals",
    description:
      "Understanding network protocols and basic concepts essential for cybersecurity.",
    category: "Fundamentals",
    difficulty: "Beginner",
    duration: "3-4 weeks",
    icon: Network,
    color: "text-purple-400",
    bgColor: "bg-purple-400/10",
    borderColor: "border-purple-400/30",
    enrolled: true,
    progress: 60,
    lessons: 26,
    labs: 15,
    games: 10,
    assets: 20,
    rating: 4.7,
    students: 6890,
    price: "Free",
    skills: ["TCP/IP", "OSI Model", "DNS", "Basic Protocols"],
    prerequisites: "Basic computer knowledge",
    certification: true,
    instructor: {
      name: "Maria Santos",
      title: "Network Security Engineer",
      avatar:
        "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150",
      experience: "10+ years in network security",
    },
    curriculum: [
      {
        title: "Network Fundamentals",
        lessons: 8,
        duration: "4h",
        topics: [
          "OSI Model",
          "Protocol Stack Builder Game",
          "TCP/IP Stack",
          "Network Topologies",
          "Basic Protocols",
          "Network Packet Analysis Lab",
        ],
        completed: true,
      },
      {
        title: "Network Protocols",
        lessons: 10,
        duration: "5h",
        topics: [
          "HTTP/HTTPS",
          "DNS",
          "DNS Configuration Lab",
          "DHCP",
          "ARP",
          "Protocol Analysis Game",
        ],
        completed: true,
      },
      {
        title: "Network Security Basics",
        lessons: 8,
        duration: "4h",
        topics: [
          "Firewalls",
          "VPNs",
          "Network Monitoring",
          "Network Scanning Exercise Lab",
          "Network Troubleshooter Game",
          "Common Attacks",
        ],
        completed: false,
      },
    ],
    learningOutcomes: [
      {
        title: "Understand network architecture",
        description:
          "Learn how networks are structured and how data flows through different layers.",
        skills: ["OSI Model", "Network Architecture", "Protocol Stack"],
      },
      {
        title: "Master essential protocols",
        description:
          "Understand key networking protocols and their security implications.",
        skills: ["TCP/IP", "DNS", "HTTP/HTTPS", "Network Protocols"],
      },
      {
        title: "Identify network vulnerabilities",
        description:
          "Recognize common network security issues and attack vectors.",
        skills: [
          "Network Security",
          "Vulnerability Assessment",
          "Attack Vectors",
        ],
      },
    ],
    labsData: [
      {
        name: "Network Packet Analysis",
        description:
          "Analyze network traffic using Wireshark to understand protocols",
        difficulty: "Beginner",
        duration: "60 min",
        skills: ["Packet Analysis", "Wireshark"],
      },
      {
        name: "DNS Configuration Lab",
        description:
          "Configure and troubleshoot DNS settings in a lab environment",
        difficulty: "Beginner",
        duration: "45 min",
        skills: ["DNS", "Network Configuration"],
      },
      {
        name: "Network Scanning Exercise",
        description:
          "Use network scanning tools to discover devices and services",
        difficulty: "Intermediate",
        duration: "75 min",
        skills: ["Network Scanning", "Reconnaissance"],
      },
      {
        name: "OSI Model Practical Lab",
        description: "Hands-on exploration of the OSI model layers",
        difficulty: "Beginner",
        duration: "50 min",
        skills: ["OSI Model", "Network Theory"],
      },
      {
        name: "TCP/IP Configuration Workshop",
        description: "Configure and troubleshoot TCP/IP settings",
        difficulty: "Intermediate",
        duration: "65 min",
        skills: ["TCP/IP", "Network Configuration"],
      },
      {
        name: "Firewall Rules Lab",
        description: "Create and test firewall rules for network security",
        difficulty: "Intermediate",
        duration: "80 min",
        skills: ["Firewall", "Network Security"],
      },
      {
        name: "VPN Setup and Configuration",
        description: "Set up and configure VPN connections",
        difficulty: "Intermediate",
        duration: "70 min",
        skills: ["VPN", "Network Security"],
      },
      {
        name: "Network Monitoring Lab",
        description: "Monitor network traffic and identify anomalies",
        difficulty: "Advanced",
        duration: "90 min",
        skills: ["Network Monitoring", "Security Analysis"],
      },
      {
        name: "Wireless Security Assessment",
        description: "Assess and secure wireless network infrastructure",
        difficulty: "Advanced",
        duration: "95 min",
        skills: ["Wireless Security", "Network Assessment"],
      },
      {
        name: "Network Forensics Workshop",
        description: "Investigate network incidents using forensic techniques",
        difficulty: "Advanced",
        duration: "110 min",
        skills: ["Network Forensics", "Incident Investigation"],
      },
      {
        name: "VLAN Configuration Lab",
        description:
          "Configure and manage Virtual LANs for network segmentation",
        difficulty: "Intermediate",
        duration: "75 min",
        skills: ["VLAN", "Network Segmentation"],
      },
      {
        name: "Network Performance Optimization",
        description:
          "Optimize network performance and troubleshoot bottlenecks",
        difficulty: "Advanced",
        duration: "100 min",
        skills: ["Performance Optimization", "Network Troubleshooting"],
      },
      {
        name: "Network Attack Simulation",
        description: "Simulate and defend against common network attacks",
        difficulty: "Advanced",
        duration: "120 min",
        skills: ["Attack Simulation", "Network Defense"],
      },
      {
        name: "Load Balancer Configuration",
        description: "Configure and test network load balancers",
        difficulty: "Advanced",
        duration: "85 min",
        skills: ["Load Balancing", "High Availability"],
      },
      {
        name: "Network Documentation Lab",
        description: "Create comprehensive network documentation and diagrams",
        difficulty: "Intermediate",
        duration: "60 min",
        skills: ["Documentation", "Network Mapping"],
      },
    ],
    gamesData: [
      {
        name: "Protocol Stack Builder",
        description:
          "Build network protocol stacks by matching layers correctly",
        points: 100,
        type: "Educational",
      },
      {
        name: "Network Troubleshooter",
        description: "Diagnose and fix network connectivity issues",
        points: 150,
        type: "Simulation",
      },
      {
        name: "Protocol Analysis Game",
        description: "Analyze network protocols and identify their functions",
        points: 120,
        type: "Analysis",
      },
      {
        name: "Packet Capture Challenge",
        description: "Capture and analyze network packets in real-time",
        points: 140,
        type: "Investigation",
      },
      {
        name: "Network Security Scanner",
        description: "Scan networks for vulnerabilities and security issues",
        points: 160,
        type: "Security",
      },
      {
        name: "Firewall Configuration Game",
        description: "Configure firewalls to protect network infrastructure",
        points: 180,
        type: "Configuration",
      },
      {
        name: "VPN Setup Simulator",
        description: "Set up and configure VPN connections securely",
        points: 170,
        type: "Simulation",
      },
      {
        name: "Network Attack Defense",
        description: "Defend against various network-based attacks",
        points: 200,
        type: "Defense",
      },
      {
        name: "DNS Security Challenge",
        description: "Secure DNS infrastructure against attacks",
        points: 130,
        type: "Security",
      },
      {
        name: "Network Forensics Game",
        description: "Investigate network incidents using forensic techniques",
        points: 190,
        type: "Forensics",
      },
    ],
    assetsData: [
      { name: "OSI Model Reference", type: "PDF", size: "1.8 MB" },
      { name: "Protocol Comparison Chart", type: "PDF", size: "900 KB" },
    ],
    enrollPath: "/learn/networking-basics",
  },
  "web-security-intro": {
    id: "web-security-intro",
    title: "Introduction to Web Security",
    description:
      "Basic web application security concepts and common vulnerabilities.",
    category: "Web Security",
    difficulty: "Beginner",
    duration: "2-3 weeks",
    icon: Shield,
    color: "text-cyan-400",
    bgColor: "bg-cyan-400/10",
    borderColor: "border-cyan-400/30",
    enrolled: true,
    progress: 40,
    lessons: 23,
    labs: 10,
    games: 7,
    assets: 15,
    rating: 4.6,
    students: 5420,
    price: "Free",
    skills: ["HTTP/HTTPS", "Authentication", "Basic XSS", "CSRF Basics"],
    prerequisites: "Basic web knowledge",
    certification: true,
    instructor: {
      name: "David Kim",
      title: "Web Security Specialist",
      avatar:
        "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150",
      experience: "8+ years in web application security",
    },
    curriculum: [
      {
        title: "Web Security Fundamentals",
        lessons: 7,
        duration: "3h 15min",
        topics: [
          "HTTP/HTTPS",
          "Web Architecture",
          "Security Headers",
          "Security Header Configurator Game",
          "Cookies",
          "Web Security Basics Lab",
        ],
        completed: true,
      },
      {
        title: "Common Web Vulnerabilities",
        lessons: 9,
        duration: "4h 30min",
        topics: [
          "XSS",
          "XSS Vulnerability Lab",
          "CSRF",
          "CSRF Attack Simulation Lab",
          "SQL Injection",
          "Web Vulnerability Hunter Game",
          "Authentication Flaws",
          "Authentication Bypass Challenge Lab",
        ],
        completed: false,
      },
      {
        title: "Web Security Testing",
        lessons: 7,
        duration: "3h 30min",
        topics: [
          "Manual Testing",
          "Automated Tools",
          "Security Scanners",
          "Web Application Testing Lab",
          "Vulnerability Scanner Game",
          "Reporting",
        ],
        completed: false,
      },
    ],
    learningOutcomes: [
      {
        title: "Understand web security fundamentals",
        description:
          "Learn the basics of how web applications work and common security mechanisms.",
        skills: ["Web Architecture", "HTTP/HTTPS", "Security Headers"],
      },
      {
        title: "Identify common vulnerabilities",
        description:
          "Recognize and understand the most common web application security flaws.",
        skills: ["XSS", "CSRF", "SQL Injection", "Authentication"],
      },
      {
        title: "Perform basic security testing",
        description:
          "Learn to test web applications for security vulnerabilities using manual and automated techniques.",
        skills: [
          "Security Testing",
          "Vulnerability Assessment",
          "Web Scanners",
        ],
      },
    ],
    labsData: [
      {
        name: "XSS Vulnerability Lab",
        description:
          "Identify and exploit cross-site scripting vulnerabilities",
        difficulty: "Beginner",
        duration: "45 min",
        skills: ["XSS", "Web Exploitation"],
      },
      {
        name: "CSRF Attack Simulation",
        description:
          "Understand and demonstrate cross-site request forgery attacks",
        difficulty: "Beginner",
        duration: "40 min",
        skills: ["CSRF", "Web Security"],
      },
      {
        name: "Authentication Bypass Challenge",
        description: "Find and exploit authentication vulnerabilities",
        difficulty: "Intermediate",
        duration: "60 min",
        skills: ["Authentication", "Web Exploitation"],
      },
      {
        name: "Web Security Basics Lab",
        description: "Explore fundamental web security concepts hands-on",
        difficulty: "Beginner",
        duration: "50 min",
        skills: ["Web Security", "HTTP/HTTPS"],
      },
      {
        name: "SQL Injection Workshop",
        description:
          "Learn to identify and exploit SQL injection vulnerabilities",
        difficulty: "Intermediate",
        duration: "75 min",
        skills: ["SQL Injection", "Database Security"],
      },
      {
        name: "Web Application Testing Lab",
        description: "Comprehensive testing of web application security",
        difficulty: "Intermediate",
        duration: "90 min",
        skills: ["Web Testing", "Security Assessment"],
      },
      {
        name: "Session Management Lab",
        description: "Analyze and exploit session management vulnerabilities",
        difficulty: "Intermediate",
        duration: "65 min",
        skills: ["Session Management", "Web Security"],
      },
      {
        name: "Input Validation Testing",
        description: "Test input validation mechanisms in web applications",
        difficulty: "Intermediate",
        duration: "55 min",
        skills: ["Input Validation", "Web Security"],
      },
      {
        name: "Web API Security Lab",
        description: "Secure and test REST API endpoints",
        difficulty: "Advanced",
        duration: "80 min",
        skills: ["API Security", "REST APIs"],
      },
      {
        name: "OWASP Top 10 Workshop",
        description: "Hands-on exploration of OWASP Top 10 vulnerabilities",
        difficulty: "Advanced",
        duration: "120 min",
        skills: ["OWASP", "Web Vulnerabilities"],
      },
    ],
    gamesData: [
      {
        name: "Web Vulnerability Hunter",
        description: "Find hidden vulnerabilities in web applications",
        points: 120,
        type: "Hunt",
      },
      {
        name: "Security Header Configurator",
        description: "Configure security headers to protect web applications",
        points: 100,
        type: "Configuration",
      },
      {
        name: "XSS Attack Simulator",
        description: "Learn to identify and exploit XSS vulnerabilities safely",
        points: 140,
        type: "Simulation",
      },
      {
        name: "SQL Injection Challenge",
        description:
          "Master SQL injection techniques in a controlled environment",
        points: 160,
        type: "Exploitation",
      },
      {
        name: "CSRF Defense Game",
        description:
          "Implement defenses against Cross-Site Request Forgery attacks",
        points: 130,
        type: "Defense",
      },
      {
        name: "Authentication Bypass Puzzle",
        description: "Find creative ways to bypass authentication mechanisms",
        points: 150,
        type: "Puzzle",
      },
      {
        name: "Web Application Firewall Game",
        description: "Configure and test web application firewalls",
        points: 170,
        type: "Configuration",
      },
    ],
    assetsData: [
      { name: "OWASP Top 10 Guide", type: "PDF", size: "2.5 MB" },
      { name: "Web Security Checklist", type: "PDF", size: "1.1 MB" },
    ],
    enrollPath: "/learn/web-security-intro",
  },
  "penetration-testing": {
    id: "penetration-testing",
    title: "Penetration Testing Fundamentals",
    description:
      "Learn ethical hacking and penetration testing basics with hands-on practice.",
    category: "Offensive Security",
    difficulty: "Intermediate",
    duration: "4-5 weeks",
    icon: Target,
    color: "text-red-400",
    bgColor: "bg-red-400/10",
    borderColor: "border-red-400/30",
    enrolled: false,
    progress: 0,
    lessons: 33,
    labs: 20,
    games: 12,
    assets: 25,
    rating: 4.9,
    students: 3240,
    price: "$49",
    skills: [
      "Reconnaissance",
      "Vulnerability Assessment",
      "Exploitation",
      "Post-Exploitation",
    ],
    prerequisites: "Networking basics, Linux command line",
    certification: true,
    instructor: {
      name: "Jake Thompson",
      title: "Senior Penetration Tester",
      avatar:
        "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150",
      experience: "12+ years in penetration testing",
    },
    curriculum: [
      {
        title: "Penetration Testing Methodology",
        lessons: 10,
        duration: "5h",
        topics: [
          "PTES Framework",
          "Scoping",
          "Rules of Engagement",
          "Legal Considerations",
          "Methodology Simulation Game",
          "Penetration Testing Planning Lab",
        ],
        completed: false,
      },
      {
        title: "Reconnaissance & Enumeration",
        lessons: 12,
        duration: "6h",
        topics: [
          "OSINT",
          "OSINT Collection Game",
          "Network Scanning",
          "Network Reconnaissance Lab",
          "Service Enumeration",
          "Enumeration Challenge Lab",
          "Vulnerability Scanning",
          "Vulnerability Assessment Game",
        ],
        completed: false,
      },
      {
        title: "Exploitation & Post-Exploitation",
        lessons: 11,
        duration: "7h",
        topics: [
          "Exploit Development",
          "Metasploit",
          "Web Application Penetration Test Lab",
          "Privilege Escalation",
          "Privilege Escalation Challenge Lab",
          "Persistence",
          "Capture the Flag Game",
          "Exploit Chain Builder Game",
        ],
        completed: false,
      },
    ],
    learningOutcomes: [
      {
        title: "Master penetration testing methodology",
        description:
          "Learn systematic approaches to penetration testing following industry standards.",
        skills: ["PTES", "Methodology", "Planning", "Scoping"],
      },
      {
        title: "Perform comprehensive reconnaissance",
        description:
          "Gather intelligence and enumerate targets using various tools and techniques.",
        skills: [
          "OSINT",
          "Reconnaissance",
          "Enumeration",
          "Intelligence Gathering",
        ],
      },
      {
        title: "Execute exploitation techniques",
        description:
          "Learn to identify, exploit, and leverage vulnerabilities in target systems.",
        skills: [
          "Exploitation",
          "Metasploit",
          "Privilege Escalation",
          "Post-Exploitation",
        ],
      },
    ],
    labsData: [
      {
        name: "Network Reconnaissance Lab",
        description: "Perform comprehensive reconnaissance on a target network",
        difficulty: "Intermediate",
        duration: "90 min",
        skills: ["Reconnaissance", "Network Scanning"],
      },
      {
        name: "Web Application Penetration Test",
        description:
          "Complete penetration test of a vulnerable web application",
        difficulty: "Intermediate",
        duration: "120 min",
        skills: ["Web Testing", "Exploitation"],
      },
      {
        name: "Privilege Escalation Challenge",
        description: "Escalate privileges on compromised systems",
        difficulty: "Advanced",
        duration: "75 min",
        skills: ["Privilege Escalation", "Post-Exploitation"],
      },
      {
        name: "Penetration Testing Planning Lab",
        description: "Plan and scope a penetration testing engagement",
        difficulty: "Beginner",
        duration: "60 min",
        skills: ["Planning", "Scoping", "Documentation"],
      },
      {
        name: "OSINT Collection Workshop",
        description: "Gather intelligence using open source techniques",
        difficulty: "Beginner",
        duration: "70 min",
        skills: ["OSINT", "Intelligence Gathering"],
      },
      {
        name: "Enumeration Challenge Lab",
        description: "Enumerate services and gather system information",
        difficulty: "Intermediate",
        duration: "85 min",
        skills: ["Enumeration", "Information Gathering"],
      },
      {
        name: "Vulnerability Assessment Lab",
        description: "Identify and assess vulnerabilities in target systems",
        difficulty: "Intermediate",
        duration: "95 min",
        skills: ["Vulnerability Assessment", "Risk Analysis"],
      },
      {
        name: "Metasploit Framework Lab",
        description: "Master the Metasploit framework for exploitation",
        difficulty: "Advanced",
        duration: "110 min",
        skills: ["Metasploit", "Exploitation"],
      },
      {
        name: "Social Engineering Lab",
        description: "Practice social engineering techniques ethically",
        difficulty: "Intermediate",
        duration: "80 min",
        skills: ["Social Engineering", "Human Psychology"],
      },
      {
        name: "Post-Exploitation Workshop",
        description: "Learn post-exploitation techniques and persistence",
        difficulty: "Advanced",
        duration: "100 min",
        skills: ["Post-Exploitation", "Persistence"],
      },
      {
        name: "Wireless Penetration Testing",
        description: "Test wireless network security",
        difficulty: "Advanced",
        duration: "105 min",
        skills: ["Wireless Security", "Network Testing"],
      },
      {
        name: "Mobile Application Testing",
        description: "Penetration test mobile applications",
        difficulty: "Advanced",
        duration: "115 min",
        skills: ["Mobile Security", "Application Testing"],
      },
      {
        name: "Red Team Exercise",
        description: "Conduct a full red team operation",
        difficulty: "Expert",
        duration: "180 min",
        skills: ["Red Teaming", "Advanced Tactics"],
      },
      {
        name: "Penetration Testing Report Lab",
        description: "Create professional penetration testing reports",
        difficulty: "Intermediate",
        duration: "90 min",
        skills: ["Report Writing", "Documentation"],
      },
      {
        name: "Cloud Penetration Testing",
        description: "Test cloud infrastructure security",
        difficulty: "Advanced",
        duration: "125 min",
        skills: ["Cloud Security", "Infrastructure Testing"],
      },
      {
        name: "Active Directory Attack Lab",
        description: "Attack and compromise Active Directory environments",
        difficulty: "Advanced",
        duration: "130 min",
        skills: ["Active Directory", "Windows Security"],
      },
      {
        name: "Buffer Overflow Exploitation",
        description: "Learn to exploit buffer overflow vulnerabilities",
        difficulty: "Expert",
        duration: "150 min",
        skills: ["Buffer Overflow", "Exploit Development"],
      },
      {
        name: "Evasion Techniques Lab",
        description: "Evade detection systems and security controls",
        difficulty: "Advanced",
        duration: "95 min",
        skills: ["Evasion", "Anti-Detection"],
      },
      {
        name: "Physical Security Assessment",
        description: "Assess physical security controls and bypasses",
        difficulty: "Intermediate",
        duration: "75 min",
        skills: ["Physical Security", "Lock Picking"],
      },
    ],
    gamesData: [
      {
        name: "Capture the Flag",
        description: "Complete penetration testing challenges to capture flags",
        points: 200,
        type: "CTF",
      },
      {
        name: "Exploit Chain Builder",
        description: "Chain multiple exploits together for maximum impact",
        points: 250,
        type: "Strategy",
      },
      {
        name: "OSINT Collection Game",
        description:
          "Gather intelligence using open source intelligence techniques",
        points: 180,
        type: "Investigation",
      },
      {
        name: "Methodology Simulation",
        description:
          "Practice penetration testing methodologies in realistic scenarios",
        points: 160,
        type: "Simulation",
      },
      {
        name: "Vulnerability Assessment Game",
        description: "Identify and assess vulnerabilities in target systems",
        points: 170,
        type: "Assessment",
      },
      {
        name: "Social Engineering Simulator",
        description:
          "Learn social engineering techniques in a safe environment",
        points: 140,
        type: "Simulation",
      },
      {
        name: "Metasploit Master",
        description:
          "Master the Metasploit framework through hands-on challenges",
        points: 220,
        type: "Technical",
      },
      {
        name: "Privilege Escalation Puzzle",
        description:
          "Find creative ways to escalate privileges on compromised systems",
        points: 240,
        type: "Puzzle",
      },
      {
        name: "Red Team Simulator",
        description:
          "Conduct full red team operations against defended networks",
        points: 300,
        type: "Advanced",
      },
      {
        name: "Persistence Challenge",
        description:
          "Maintain access to compromised systems using various techniques",
        points: 210,
        type: "Stealth",
      },
      {
        name: "Evasion Techniques Game",
        description: "Evade detection systems and security controls",
        points: 230,
        type: "Evasion",
      },
      {
        name: "Reporting Master",
        description: "Create professional penetration testing reports",
        points: 120,
        type: "Documentation",
      },
    ],
    assetsData: [
      { name: "Penetration Testing Methodology", type: "PDF", size: "3.2 MB" },
      { name: "Metasploit Quick Reference", type: "PDF", size: "1.8 MB" },
    ],
    enrollPath: "/learn/penetration-testing",
  },
};

export const getCourseById = (courseId: string): Course | null => {
  return coursesData[courseId] || null;
};

export const getAllCourses = (): Course[] => {
  return Object.values(coursesData);
};
